#!/bin/sh /etc/rc.common
# Copyright (C) 2012-2014 OpenWrt.org

START=90

USE_PROCD=1
PROG="/usr/sbin/easycwmpd"

UCI_SET="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} set"
UCI_COMMIT="/sbin/uci -q ${UCI_CONFIG_DIR:+-c $UCI_CONFIG_DIR} commit"
init_device_info() {
	local val
	val=`uci -q get network.wan.ifname`
	[ -n "$val" ] && $UCI_SET easycwmp.@local[0].interface="$val"

	$UCI_COMMIT easycwmp
}

start_service() {
	if [ "`uci get easycwmp.@acs[0].periodic_enable`" == "1" ]; then
		init_device_info
		procd_open_instance
		procd_set_param command "$PROG" -f
		#if [ "$1" = "--boot" ];then
			procd_append_param command --boot
		#else
			procd_append_param command --getrpcmethod
		#fi
		procd_set_param respawn "3" "7" "0"
		procd_close_instance
	fi
}

boot() {
	start --boot
}

#service_triggers()
#{
#	procd_add_reload_trigger "/etc/config/easycwmp"
#}
