#!/bin/sh /etc/rc.common
# Copyright (C) 2006 OpenWrt.org

START=50

. /lib/functions.sh
ENABLED=0

boot() {
	/usr/lib/qos/generate.sh firewall | sh
}

checkifenabled() {
	config_get_bool enabled "$1" 'enabled' 0
	if [ $enabled -eq 1 ]; then
		ENABLED=1
	fi
}

start() {
	config_load 'qos'
	config_foreach checkifenabled 'interface'
	[ $ENABLED -eq 0 ] && return 1
	/usr/lib/qos/generate.sh all | sh
}

stop() {
	for iface in $(tc qdisc show | grep -E '(hfsc|ingress)' | awk '{print $5}'); do
		tc qdisc del dev "$iface" ingress 2>&- >&-
		tc qdisc del dev "$iface" root 2>&- >&-
	done
	/usr/lib/qos/generate.sh firewall stop | sh
}

reload() {
	stop
	start
}
