#!/bin/sh /etc/rc.common

# Copyright (C) 2014 Teltonika

#START=55
STOP=45
USE_PROCD=1

. /lib/teltonika-functions.sh
module_vidpid=`get_ext_vidpid_tlt`

GPSD_BIN="/usr/sbin/gpsd"

start_service() {
	if [[ "`uci get -q gps.gps.enabled`" == "1" && "`uci get -q hwinfo.hwinfo.gps`" == "1" ]]; then
		start_nmea
		procd_open_instance
		procd_set_param respawn
		procd_set_param command "$GPSD_BIN"
		procd_close_instance
	fi
}

stop_service() {
	#killall gpsd 2>/dev/null >/dev/null
	case "$module_vidpid" in
		12D1:1573)
			gsmctl -A AT^WPEND 2>/dev/null >/dev/null
			;;
		05C6:9215)
			gsmctl -A AT+QGPSEND 2>/dev/null >/dev/null
			;;
		1199:68C0)
			stty raw -F /dev/gps; echo \$GPS_STOP >/dev/gps
			;;
		*)
			echo "$0: unknown or no GPS device, aborting"
			;;
	esac
}

start_nmea() {
	case "$module_vidpid" in
		12D1:1573)
			gsmctl -A AT^WPDOM=0 2>/dev/null >/dev/null
			gsmctl -A AT^WPDST=1 2>/dev/null >/dev/null
			gsmctl -A AT^WPDFR=0,1 2>/dev/null >/dev/null
			gsmctl -A AT^WPQOS=255,500 2>/dev/null >/dev/null
			gsmctl -A AT^WPDGP 2>/dev/null >/dev/null
			;;
		05C6:9215)
			gsmctl -A AT+QGPS=1 2>/dev/null >/dev/null
			;;
		1199:68C0)
			stty raw -F /dev/gps; echo \$GPS_START >/dev/gps
			;;
		*)
			echo "$0: unknown or no GPS device, aborting"
			;;
	esac
}

reload_service(){
	stop
	start
}
