#!/bin/sh /etc/rc.common

USE_PROCD=1
START=70
STOP=40

start_service() {
	#local enabled=`uci get mdcollectd.config.enabled`
	#if [ "$enabled" = "1" ]; then
		procd_open_instance
		procd_set_param respawn
		procd_set_param command /usr/bin/mdcollectd start
		procd_close_instance
	#fi
}

stop_service() {
	/usr/bin/mdcollectd stop
}

restart () {
	/usr/bin/mdcollectd restart &
}

reload_service() {
	stop
	start
} 

status () {
	/usr/bin/mdcollectd status
}
