#!/bin/sh /etc/rc.common

USE_PROCD=1
START=14
STOP=99

SERIAL="rs232"
ENABLED=`uci -q get rs."$SERIAL".enabled`

check_value(){
	value="$1"
	variable="$2"

	if [ "$value" == "" ]; then
		echo "$value"
	else
		echo "-$variable "$value""
	fi
}

if [ "$ENABLED" = "1" ]; then
	TYPE=`uci -q get rs."$SERIAL".type`
	SPEED=`uci -q get rs."$SERIAL".baudrate`
	DBITS=`uci -q get rs."$SERIAL".databits`
	PARITY=`uci -q get rs."$SERIAL".parity`
	SBITS=`uci -q get rs."$SERIAL".stopbits`
	FCTRL=`uci -q get rs."$SERIAL".flowcontrol`

	case "$PARITY" in
		"none")	PARITY_TMP="-parenb -parodd";;
		"odd")	PARITY_TMP="parenb parodd";;
		"even")	PARITY_TMP="parenb -parodd";;
		*)		PARITY_TMP="-parenb -parodd";;
	esac

	case "$SBITS" in
		1) SBITS_TMP="-cstopb";;
		2) SBITS_TMP="cstopb";;
		*) SBITS_TMP="-cstopb";;
	esac

	case "$FCTRL" in
		"none")		FCTRL_TMP="-crtscts -ixon -ixoff";;
		"rts/cts")	FCTRL_TMP="crtscts";;
		"xon/xoff")	FCTRL_TMP="ixon ixoff";;
		*)			FCTRL_TMP="-crtscts -ixon -ixoff";;
	esac

	/bin/stty -F /dev/"$SERIAL" "$SPEED" cs"$DBITS" $PARITY_TMP "$SBITS_TMP" $FCTRL_TMP

	if [ "$TYPE" = "console" ]; then
		start_service() {
			procd_open_instance
			procd_set_param command /sbin/getty "$SPEED" /dev/"$SERIAL" vt100
			procd_set_param respawn
			procd_close_instance
		}
	elif [ "$TYPE" = "overip" ]; then
		MODE=`uci -q get rs."$SERIAL".mode`

		SBITS=`check_value "$SBITS" "t"`
		DBITS=`check_value "$DBITS" "b"`
		SPEED=`check_value "$SPEED" "s"`
		PARITY=`check_value "$PARITY" "a"`

		if [ "$MODE" = "server" ]; then
			MODE=`check_value "$MODE" "m"`
			TIMEOUT=`uci -q get rs."$SERIAL".timeout`
			TIMEOUT=`check_value "$TIMEOUT" "c"`
			IP_LISTEN=`uci -q get rs."$SERIAL".ip_listen`
			IP_LISTEN=`check_value "$IP_LISTEN" "i"`
			PORT_LISTEN=`uci -q get rs."$SERIAL".port_listen`
			PORT_LISTEN=`check_value "$PORT_LISTEN" "g"`

			DEBUG_LEVEL=`uci -q get rs."$SERIAL".debug`
			DEBUG_LEVEL=`check_value "$DEBUG_LEVEL" "D"`

			start_service() {
				procd_open_instance
				procd_set_param command /usr/sbin/sodog -p "/dev/$SERIAL" $DBITS $SPEED $PARITY $SBITS $MODE $DEBUG_LEVEL $TIMEOUT $IP_LISTEN $PORT_LISTEN
				procd_set_param respawn
				procd_close_instance

			}
		elif [ "$MODE" = "client" ]; then
			MODE=`check_value "$MODE" "m"`
			INTERVAL=`uci -q get rs."$SERIAL".recon_interval`
			INTERVAL=`check_value "$INTERVAL" "y"`
			IP_CONNECT=`uci -q get rs."$SERIAL".ip_connect`
			IP_CONNECT=`check_value "$IP_CONNECT" "l"`
			PORT_CONNECT=`uci -q get rs."$SERIAL".port_connect`
			PORT_CONNECT=`check_value "$PORT_CONNECT" "k"`

			DEBUG_LEVEL=`uci -q get rs."$SERIAL".debug`
			DEBUG_LEVEL=`check_value "$DEBUG_LEVEL" "D"`
			start_service() {
				procd_open_instance
				procd_set_param command /usr/sbin/sodog -p "/dev/$SERIAL" $DBITS $SPEED $PARITY $SBITS $MODE $DEBUG_LEVEL $IP_CONNECT $PORT_CONNECT $INTERVAL
				procd_set_param respawn
				procd_close_instance
			}
		elif [ "$MODE" = "bidirect" ]; then
			MODE=`check_value "$MODE" "m"`
			GPIO=`uci -q get rs."$SERIAL".gpio`
			GPIO=`check_value "$GPIO" "u"`
			GPIOSTATE=`uci -q get rs."$SERIAL".gpiostate`
			GPIOSTATE=`check_value "$GPIOSTATE" "j"`

			TIMEOUT=`uci -q get rs."$SERIAL".timeout`
			TIMEOUT=`check_value "$TIMEOUT" "c"`
			IP_LISTEN=`uci -q get rs."$SERIAL".ip_listen`
			IP_LISTEN=`check_value "$IP_LISTEN" "i"`
			PORT_LISTEN=`uci -q get rs."$SERIAL".port_listen`
			PORT_LISTEN=`check_value "$PORT_LISTEN" "g"`

			INTERVAL=`uci -q get rs."$SERIAL".recon_interval`
			INTERVAL=`check_value "$INTERVAL" "y"`
			IP_CONNECT=`uci -q get rs."$SERIAL".ip_connect`
			IP_CONNECT=`check_value "$IP_CONNECT" "l"`
			PORT_CONNECT=`uci -q get rs."$SERIAL".port_connect`
			PORT_CONNECT=`check_value "$PORT_CONNECT" "k"`

			DEBUG_LEVEL=`uci -q get rs."$SERIAL".debug`
			DEBUG_LEVEL=`check_value "$DEBUG_LEVEL" "D"`

			start_service() {
				procd_open_instance
				procd_set_param command /usr/sbin/sodog -p "/dev/$SERIAL" $DBITS $SPEED $PARITY $SBITS $MODE $DEBUG_LEVEL $IP_CONNECT $PORT_CONNECT $INTERVAL $TIMEOUT $IP_LISTEN $PORT_LISTEN $GPIO $GPIOSTATE
				procd_set_param respawn
				procd_close_instance
			}
		fi
	elif [ "$TYPE" = "modem" ]; then
		DCONNECT=`uci -q get rs."$SERIAL".direct_connect`
		PORT=`uci -q get rs."$SERIAL".modem_port`
		[ -n "$DCONNECT" ] && PARAMS="$PARAMS -D $DCONNECT"
		[ -n "$PORT" ] && PARAMS="$PARAMS -p $PORT"
		start_service() {
			procd_open_instance
			procd_set_param command /usr/bin/tcpser -s "$SPEED" -d "/dev/$SERIAL" $PARAMS
			procd_set_param respawn
			procd_close_instance
		}
	elif [ "$TYPE" = "modbus" ]; then
		MODBUS_IP=`uci -q get rs."$SERIAL".modbus_ip`
		MODBUS_PORT=`uci -q get rs."$SERIAL".modbus_port`
		
		SLAVE_ID=`uci -q get rs."$SERIAL".slave_id`
		SLAVE_ID_CONFIG=`uci -q get rs."$SERIAL".slave_id_config`
		MULTI_SLAVE_ID=`uci -q get rs."$SERIAL".multi_slave_id`
		SINGLE_SLAVE_ID=`uci -q get rs."$SERIAL".single_slave_id`
		
		start_service() {
			echo "$MULTI_SLAVE_ID"
			procd_open_instance
			if [ "$SLAVE_ID_CONFIG" = "single" ]; then
				procd_set_param command /usr/sbin/modbusgwd -p /dev/"$SERIAL" -s "$SPEED" -b "$DBITS" -a "$PARITY" -t "$SBITS" -g "$SINGLE_SLAVE_ID" -i "$MODBUS_IP" -m "$MODBUS_PORT"
			else
				procd_set_param command /usr/sbin/modbusgwd -p /dev/"$SERIAL" -s "$SPEED" -b "$DBITS" -a "$PARITY" -t "$SBITS" -r "$MULTI_SLAVE_ID" -i "$MODBUS_IP" -m "$MODBUS_PORT"
			fi				
			procd_set_param respawn
			procd_close_instance
		}
	fi
fi
