#!/usr/bin/lua
io.stdout:write("Content-Type: text/plain\r\n\r\n")

require "teltonika_lua_functions"
require("uci")
local uci = uci.cursor()

function exec(command)
	local pp   = io.popen(command)
	local data = pp:read("*a")
	pp:close()
	data = data:gsub("^%s*(.-)%s*$", "%1")
	return data
end

function url_decode(str)
	if not str then return nil end
	str = string.gsub (str, "+", " ")
	str = string.gsub (str, "%%(%x%x)", function(h) return
		string.char(tonumber(h,16)) end)
	str = string.gsub (str, "\r\n", "\n")
	return str
end

function url_parse(url)
	local params = {}
	for s in string.gmatch(url, "[^&]+") do
		for k, v in string.gmatch(s, "(.-)=(.*)") do
			params[k] = v
		end
	end
	return params
end

function gpio_action(action, pin)
	local gpio = "/sbin/gpio.sh"
	local command = string.format("%s %s %s",gpio , action, pin)
	if not getParam(command)then
		return "OK"
	end
	return
end

function debug(string)
	os.execute("logger " ..string)
end

if os.getenv("QUERY_STRING") then
	query = os.getenv("QUERY_STRING")
end

local enabled = uci:get("output_control", "post_get", "enabled")

if enabled == "1" then
	if query then
		query = url_decode(query)
		params = url_parse(query)
		if params['username'] and params['username'] ~= "" and params['password'] and params['password'] ~= "" and params['action'] and params['action'] ~= "" and params['pin'] and params['pin'] ~= "" then
			username = uci:get("output_control","post_get","username")
			password = uci:get("output_control","post_get","password")
			if params['username'] == username and params['password'] == password then
				local action
				local pin
				
				if params['action'] == "on" then
					action = "set"
				elseif params['action'] == "off" then
					action = "clear"
				else
					io.stdout:write("ERROR: Action not available.")
					return
				end
				
				if params['pin'] == "oc" then
					pin = "DOUT1"
				elseif params['pin'] == "relay" then
					pin = "DOUT2"
				else
					io.stdout:write("ERROR: No such output available. (oc, relay)")
					return
				end
				
				if action and pin then
					if params['time'] and params['time'] ~= "" then
						local current_gpio = getParam("/sbin/gpio.sh get " .. pin)
						local current_action
						if current_gpio == "1" then
							current_action = "set"
						else
							current_action = "clear"
						end
						gpio_action(action, pin)
						sleep(tonumber(params['time']))
						io.stdout:write(gpio_action(current_action, pin))
					else
						io.stdout:write(gpio_action(action, pin))
					end
				end
			else
				io.stdout:write("ERROR: Unknown user name or bad password.")
			end
		else
			io.stdout:write("ERROR: Too few parameters. Expected 4 min.")
		end
	else
		io.stdout:write("ERROR: Can't get query string.")
	end
else
	io.stdout:write("ERROR: Not enabled.")
end
